# Generated by Django 4.1.9 on 2023-05-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinfo',
            name='wh_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='仓库名称'),
        ),
    ]
