# Generated by Django 4.1.7 on 2023-06-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderinfo",
            name="transport",
        ),
        migrations.AddField(
            model_name="transportrecord",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.orderinfo",
                verbose_name="订单编号",
            ),
        ),
    ]
