# Generated by Django 4.1.7 on 2023-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0002_remove_orderinfo_transport_transportrecord_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, verbose_name="订单编号"
            ),
        ),
    ]
