# Generated by Django 4.1.7 on 2023-04-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderinfo",
            name="order_realprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_birth",
            field=models.DateTimeField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_department",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="所属部门"
            ),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_gender",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="员工编号"
            ),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_job",
            field=models.TextField(blank=True, null=True, verbose_name="职务"),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_name",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="员工姓名"
            ),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_onboarddate",
            field=models.DateTimeField(blank=True, null=True, verbose_name="上岗日期"),
        ),
        migrations.AlterField(
            model_name="staffinfo",
            name="s_salary",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="基本工资"),
        ),
    ]
