# Generated by Django 4.1.7 on 2023-04-18 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fresh", "0002_alter_orderinfo_order_realprice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transportationinfo",
            options={"verbose_name": "载具信息", "verbose_name_plural": "载具信息"},
        ),
        migrations.RemoveField(
            model_name="goodsinfo",
            name="g_class",
        ),
        migrations.RemoveField(
            model_name="kpiinfo",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="kpiinfo",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="transferinfo",
            name="transfer_staffname",
        ),
        migrations.AddField(
            model_name="goodsinfo",
            name="g_category",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="货物种类"
            ),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="buy_id",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="批次编码"
            ),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="buy_intime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="到达日期"),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="buy_pdate",
            field=models.DateTimeField(blank=True, null=True, verbose_name="生产日期"),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="buy_price",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="采购价格"),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="buy_quantity",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="采购数量"),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="buy_valid",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="是否生效"
            ),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="g",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="fresh.goodsinfo",
                verbose_name="货物编码",
            ),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="return_reason",
            field=models.TextField(
                blank=True,
                db_collation="Chinese_PRC_CI_AS",
                null=True,
                verbose_name="退货原因",
            ),
        ),
        migrations.AlterField(
            model_name="buyrecord",
            name="wh",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.warehouseinfo",
                verbose_name="仓库编码",
            ),
        ),
        migrations.AlterField(
            model_name="countrecord",
            name="count_date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="盘点日期"),
        ),
        migrations.AlterField(
            model_name="countrecord",
            name="count_match",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="是否匹配"
            ),
        ),
        migrations.AlterField(
            model_name="countrecord",
            name="count_quantity",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="现有库存"),
        ),
        migrations.AlterField(
            model_name="countrecord",
            name="g",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="fresh.goodsinfo",
                verbose_name="货物编码",
            ),
        ),
        migrations.AlterField(
            model_name="countrecord",
            name="wh",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.warehouseinfo",
                verbose_name="仓库编码",
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_brand",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="货物品牌"
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_humidity",
            field=models.FloatField(blank=True, null=True, verbose_name="储存湿度"),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="货物编号"
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_life",
            field=models.DateTimeField(blank=True, null=True, verbose_name="保质期"),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_loc",
            field=models.TextField(blank=True, null=True, verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_name",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="货物名称"
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_tempreture",
            field=models.FloatField(blank=True, null=True, verbose_name="储存温度"),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_vendor",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="供应商"
            ),
        ),
        migrations.AlterField(
            model_name="kpiinfo",
            name="k_ym",
            field=models.DateTimeField(
                primary_key=True, serialize=False, verbose_name="年月"
            ),
        ),
        migrations.AlterField(
            model_name="kpiinfo",
            name="kpi",
            field=models.FloatField(blank=True, null=True, verbose_name="绩效"),
        ),
        migrations.AlterField(
            model_name="kpiinfo",
            name="realsalary",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="实发工资"),
        ),
        migrations.AlterField(
            model_name="kpiinfo",
            name="s",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.staffinfo",
                verbose_name="员工编号",
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="client_addr",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="客户地址"
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="client_name",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="客户姓名"
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="client_tel",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="客户电话"
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="g",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.goodsinfo",
                verbose_name="货物编码",
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="订单编号"
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_quantity",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="订单数量"),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_realprice",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="实际售价",
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="生效时间"),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.outboundrecord",
                verbose_name="出库编号",
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="transfer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.transferinfo",
                verbose_name="交易编码",
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="transport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.transportrecord",
                verbose_name="运输编码",
            ),
        ),
        migrations.AlterField(
            model_name="outboundrecord",
            name="g",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.goodsinfo",
                verbose_name="货物编码",
            ),
        ),
        migrations.AlterField(
            model_name="outboundrecord",
            name="out_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="出库编号"
            ),
        ),
        migrations.AlterField(
            model_name="outboundrecord",
            name="out_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="出库时间"),
        ),
        migrations.AlterField(
            model_name="outboundrecord",
            name="wh",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.warehouseinfo",
                verbose_name="仓库编码",
            ),
        ),
        migrations.AlterField(
            model_name="stockinfo",
            name="g",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.goodsinfo",
                verbose_name="货物编码",
            ),
        ),
        migrations.AlterField(
            model_name="stockinfo",
            name="s_quantity",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="库存数量"),
        ),
        migrations.AlterField(
            model_name="stockinfo",
            name="wh",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="fresh.warehouseinfo",
                verbose_name="仓库编码",
            ),
        ),
        migrations.AlterField(
            model_name="transferinfo",
            name="transfer_amount",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="金额"),
        ),
        migrations.AlterField(
            model_name="transferinfo",
            name="transfer_class",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="转账类型"
            ),
        ),
        migrations.AlterField(
            model_name="transferinfo",
            name="transfer_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="交易编码"
            ),
        ),
        migrations.AlterField(
            model_name="transferinfo",
            name="transfer_inaccount",
            field=models.CharField(
                blank=True, max_length=19, null=True, verbose_name="收款账户"
            ),
        ),
        migrations.AlterField(
            model_name="transferinfo",
            name="transfer_outaccount",
            field=models.CharField(
                blank=True, max_length=19, null=True, verbose_name="付款账户"
            ),
        ),
        migrations.AlterField(
            model_name="transferinfo",
            name="transfer_staffid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="业务员编号",
            ),
        ),
        migrations.AlterField(
            model_name="transportationinfo",
            name="driver_id",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="驾驶人编号"
            ),
        ),
        migrations.AlterField(
            model_name="transportationinfo",
            name="driver_name",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="驾驶人姓名"
            ),
        ),
        migrations.AlterField(
            model_name="transportationinfo",
            name="transportation_class",
            field=models.TextField(blank=True, null=True, verbose_name="载具类型"),
        ),
        migrations.AlterField(
            model_name="transportationinfo",
            name="transportation_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="载具编号"
            ),
        ),
        migrations.AlterField(
            model_name="transportrecord",
            name="transport_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="运输编码"
            ),
        ),
        migrations.AlterField(
            model_name="transportrecord",
            name="transport_predicatedtime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="预计送达时间"),
        ),
        migrations.AlterField(
            model_name="transportrecord",
            name="transport_realtime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="实际送达时间"),
        ),
        migrations.AlterField(
            model_name="transportrecord",
            name="transport_to",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="目的地"
            ),
        ),
        migrations.AlterField(
            model_name="transportrecord",
            name="transportation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.transportationinfo",
                verbose_name="载具编号",
            ),
        ),
        migrations.AlterField(
            model_name="transportrecord",
            name="wh",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.warehouseinfo",
                verbose_name="仓库编码",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseinfo",
            name="wh_chief",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="责任人",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseinfo",
            name="wh_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, verbose_name="仓库编号"
            ),
        ),
        migrations.AlterField(
            model_name="warehouseinfo",
            name="wh_loc",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="仓库位置"
            ),
        ),
    ]
