# Generated by Django 4.1.7 on 2023-04-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0003_alter_transportationinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpiinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="kpiinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
        ),
    ]
