# Generated by Django 4.1.7 on 2023-04-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0004_kpiinfo_created_at_kpiinfo_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpiinfo",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="kpiinfo",
            name="updated_at",
        ),
    ]
