# Generated by Django 4.1.7 on 2023-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0005_remove_kpiinfo_created_at_remove_kpiinfo_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderinfo",
            name="order_time",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="生效时间"),
        ),
    ]
