# Generated by Django 4.1.7 on 2023-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0007_alter_goodsinfo_g_humidity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseinfo",
            name="wh_loc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="仓库位置"
            ),
        ),
    ]
