# Generated by Django 4.1.7 on 2023-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0009_goodsinfo_g_production_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_category",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="货物种类"
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_life",
            field=models.DateField(blank=True, null=True, verbose_name="保质期"),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_name",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="货物名称"
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_vendor",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="供应商"
            ),
        ),
    ]
