# Generated by Django 4.1.7 on 2023-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0010_alter_goodsinfo_g_category_alter_goodsinfo_g_life_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsinfo",
            name="g_life",
            field=models.IntegerField(blank=True, null=True, verbose_name="保质期"),
        ),
    ]
