# Generated by Django 4.1.9 on 2023-06-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpiinfo',
            old_name='s_user',
            new_name='k_user',
        ),
    ]
